spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name:  com.mysql.cj.jdbc.Driver
  ##Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: com.bouali.gestiondestock.Interceptor.Interceptor
    ##Hibernate DDL Auto (create,create-drop,update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081

flickr:
  apiKey: d7ba7e92a1d826d6116e38f40ddc22cb
  apiSecret:  0a8c20d1084d8668
  appKey: 72157720866468106-1efcf9c8e14c74a5
  appSecret:  277237bdfc096841

  mvc:
    pathmatch:
      matching-strategy:  ant_path_matcher